name: Release to .zip

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: setup-node
        name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - id: setup-pnpm
        name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - id: install-deps
        name: Install dependencies
        run: pnpm install

      - id: build
        name: Build
        run: pnpm weaver build

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
